apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: docker push nikitha2109/your-image-name:1.0.2
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: <imagePullSecrets>
